platform :ios, '9.0'
target 'DeviceControl' do
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
pod 'Alamofire'
pod 'ReachabilitySwift'
pod 'PubNub', '~>4.0'
pod 'Google/SignIn'
pod 'GoogleSignIn'
pod 'Firebase/Core'
pod 'ToastSwift'
end

